# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20171102_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='path',
            new_name='local_path',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='edition',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='number_in_edition',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='original_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
