# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20171103_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='card',
            name='number_in_edition',
        ),
        migrations.RemoveField(
            model_name='card',
            name='original_path',
        ),
    ]
